import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :tvplayer, TvplayerWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# SSL redirects are disabled so Unraid / LAN HTTP access works out of the box.
# If you terminate TLS at a reverse proxy, set PHX_SCHEME=https and optionally
# enable force_ssl here with rewrite_on: [:x_forwarded_proto].
# config :tvplayer, TvplayerWeb.Endpoint,
#   force_ssl: [rewrite_on: [:x_forwarded_proto]]

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
